package debloater.service;

import debloater.model.DebloatAction;

import java.util.List;

/**
 * Generates a temporary PowerShell script from selected DebloatAction entries.
 * Only includes helper functions that are actually needed by the selected actions.
 * The generated script:
 * - Checks for admin privileges at the start
 * - Includes Ensure-RegistryPath only if needed
 * - Includes structured JSON result helper functions
 * - Wraps each action in try/catch
 * - Continues executing remaining actions even if one fails
 * - Emits machine-readable JSON result lines for parsing
 */
public class PowerShellScriptBuilder {

    /**
     * Builds the complete PowerShell script content for the given list of actions.
     * The actions must already be validated against the ActionRegistry.
     */
    public String buildScript(List<DebloatAction> actions) {
        StringBuilder sb = new StringBuilder();

        // Script header
        sb.append(buildHeader());

        // Admin check at the start
        sb.append(buildAdminCheck());

        // Check if any action needs the Ensure-RegistryPath helper
        boolean needsRegistryHelper = actions.stream().anyMatch(DebloatAction::isNeedsRegistryHelper);
        if (needsRegistryHelper) {
            sb.append(buildEnsureRegistryPathHelper());
        }

        // Always include the structured result helper functions
        sb.append(buildResultHelpers());

        // Add each selected action with a clear label
        for (int i = 0; i < actions.size(); i++) {
            DebloatAction action = actions.get(i);
            sb.append(buildActionSection(action, i + 1, actions.size()));
        }

        // Script footer
        sb.append(buildFooter());

        return sb.toString();
    }

    private String buildHeader() {
        return """
            # ============================================================
            #  Windows 11 Debloater — Generated Script
            #  Generated by Win11 Debloater App
            #  This script was generated based on your selected actions.
            #  Do not edit this file manually.
            # ============================================================

            """;
    }

    private String buildAdminCheck() {
        return """
            # ============================================================
            #  Admin Check
            # ============================================================
            If (-NOT ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) {
                Write-Warning "This script requires Administrator privileges. Please run as Administrator."
                Exit 1
            }

            """;
    }

    private String buildEnsureRegistryPathHelper() {
        return """
            # ============================================================
            #  Helper: Ensure a registry path exists
            # ============================================================
            function Ensure-RegistryPath($path) {
                If (!(Test-Path $path)) {
                    New-Item -Path $path -Force | Out-Null
                }
            }

            """;
    }

    private String buildResultHelpers() {
        return """
            # ============================================================
            #  Structured Result Helpers
            #  Each action emits a JSON line that the app parses.
            # ============================================================

            function New-ActionResult {
                param(
                    [string]$id,
                    [string]$title,
                    [string]$category,
                    [string]$riskLevel
                )
                return @{
                    id = $id
                    title = $title
                    category = $category
                    riskLevel = $riskLevel
                    status = "Pending"
                    message = ""
                    details = ""
                    error = $null
                    restartRecommended = $false
                    timestamp = (Get-Date -Format "yyyy-MM-ddTHH:mm:ss")
                }
            }

            function Write-ActionResultJson {
                param([hashtable]$result)
                $result.timestamp = (Get-Date -Format "yyyy-MM-ddTHH:mm:ss")
                $json = $result | ConvertTo-Json -Compress
                Write-Output "ACTION_RESULT:$json"
            }

            function Complete-ActionResult {
                param(
                    [hashtable]$result,
                    [string]$message,
                    [string]$details = ""
                )
                $result.status = "Success"
                $result.message = $message
                $result.details = $details
                Write-ActionResultJson -result $result
            }

            function Fail-ActionResult {
                param(
                    [hashtable]$result,
                    [string]$message,
                    [string]$error = ""
                )
                $result.status = "Failed"
                $result.message = $message
                $result.error = $error
                Write-ActionResultJson -result $result
            }

            function Skip-ActionResult {
                param(
                    [hashtable]$result,
                    [string]$message,
                    [string]$details = ""
                )
                $result.status = "Skipped"
                $result.message = $message
                $result.details = $details
                Write-ActionResultJson -result $result
            }

            function Partial-ActionResult {
                param(
                    [hashtable]$result,
                    [string]$message,
                    [string]$details = ""
                )
                $result.status = "Partially completed"
                $result.message = $message
                $result.details = $details
                Write-ActionResultJson -result $result
            }

            function AlreadyApplied-ActionResult {
                param(
                    [hashtable]$result,
                    [string]$message,
                    [string]$details = ""
                )
                $result.status = "Already applied"
                $result.message = $message
                $result.details = $details
                Write-ActionResultJson -result $result
            }

            """;
    }

    /**
     * Wraps an individual action's PowerShell block with a labeled section header.
     */
    private String buildActionSection(DebloatAction action, int index, int total) {
        return String.format("""
            # ============================================================
            #  [%d/%d] %s (%s)
            #  Category: %s | Risk: %s
            # ============================================================
            Write-Host "`n[%d/%d] %s..." -ForegroundColor Cyan

            %s

            """,
            index, total, action.getTitle(), action.getId(),
            action.getCategory().getLabel(), action.getRiskLevel().getLabel(),
            index, total, action.getTitle(),
            action.getPowerShellBlock().trim()
        );
    }

    private String buildFooter() {
        return """
            # ============================================================
            #  Script Complete
            # ============================================================
            Write-Host "`n============================================================" -ForegroundColor Green
            Write-Host "  All selected actions have been processed." -ForegroundColor Green
            Write-Host "============================================================" -ForegroundColor Green
            """;
    }
}
